name: Linux

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install RPM build tools
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Build Linux Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          skip_build: true
          github_token: ${{ secrets.github_token }}
          args: "--linux appimage deb rpm --x64 --arm64"
          release: ${{ inputs.release }}
