name: Windows

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build Windows Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          args: "--ia32 --x64 --arm64"
          release: ${{ inputs.release }}
